import the 433 initial Chris's and I annotated data (starting from some questions) and adding all of those which do have missing questions with my annotations (Jade)

In [1]:
import pickle
import pandas as pd

In [7]:
jade = pd.read_csv('./jade_prior.csv', sep='\t', index_col=0)
prior = pd.read_csv('./correction.tsv', sep='\t', index_col=0)

In [8]:
jade.head()

,index,username,gender,year,field,beerslaw,jade_label,flag_jade_label
0,434,bezdgyya,1.0,2nd,Chemistry,Wir haben es im Unterricht behandelt und auch ...,"rusty,in class",1.0
1,435,y7p64n6z,4.0,2nd,Chemistry,Eher nicht so,"heard about,no mention",NaN
2,436,892r4czm,1.0,2nd,Chemistry,Einigermassen\r\nSchon mal angeschaut und Grun...,"rusty,no mention",NaN
3,437,uhbpoog9,1.0,1st,Chemistry,Ich habe es fast nicht gekannt,"don't know,no mention",NaN
4,438,bed4zkv2,1.0,1st,Chemistry,Über haubt nicht ich wusste noch nichts davon.,"don't know,no mention",NaN

In [9]:
prior.head()

,index,username,gender,year,field,beerslaw,Chris granular,Jade granular,flag_jade_label,flag_chris_label,decisions,D,FLAG
0,0,7sfwehhm,2.0,2nd,Chemistry,missing,unknown,unknown,NaN,NaN,v,NaN,NaN
1,1,786zpupn,1.0,1st,Chemistry,nicht sehr,don't know,don't know,NaN,NaN,v,NaN,NaN
2,2,pt2nbb4w,2.0,1st,Chemistry,Ich wusste noch nichts zu diesem Thema.,don't know,don't know,NaN,NaN,v,NaN,NaN
3,3,sqrqdsge,2.0,1st,Chemistry,Fast gar nicht,don't know,don't know,NaN,NaN,v,NaN,NaN
4,4,h8624awf,1.0,2nd,Biology,Gut,"know,no mention","know,no mention",NaN,NaN,v,NaN,NaN

In [10]:
jade['Chris granular'] = -1
jade['Jade granular'] = jade['label']
jade['flag_chris_label'] = -1
jade['decisions'] = 'v'
jade['D'] = 'Was not sampled by Chris'
jade['flag'] = -1

,index,username,gender,year,field,beerslaw,jade_label,flag_jade_label,Chris granular,Jade granular,flag_chris_label,decisions,D,FLAG
0,434,bezdgyya,1.0,2nd,Chemistry,Wir haben es im Unterricht behandelt und auch ...,"rusty,in class",1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,435,y7p64n6z,4.0,2nd,Chemistry,Eher nicht so,"heard about,no mention",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,436,892r4czm,1.0,2nd,Chemistry,Einigermassen\r\nSchon mal angeschaut und Grun...,"rusty,no mention",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,437,uhbpoog9,1.0,1st,Chemistry,Ich habe es fast nicht gekannt,"don't know,no mention",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,438,bed4zkv2,1.0,1st,Chemistry,Über haubt nicht ich wusste noch nichts davon.,"don't know,no mention",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,429,etxwsdtx,2.0,3rd,"Chemistry, Textiles",o8zvguhj,NaN,1.0,unknown,don't know,1.0,unknown,NaN,Rein put ranking
430,430,u5ebbg3v,1.0,3rd,"Chemistry, Textiles","Es ist eines dieser Schulthemen, in die ich sc...",NaN,NaN,"rusty,in class","forgot,in class",NaN,"rusty,in class","More rusty, even though there is the mention o...",NaN
431,431,bm89te3c,2.0,3rd,"Chemistry, Textiles",n.a,NaN,NaN,unknown,unknown,NaN,v,NaN,NaN
432,432,missing,NaN,2nd,NaN,missing,NaN,NaN,unknown,unknown,NaN,v,NaN,NaN
433,433,3pz22p3a,1.0,3rd,Chemistry,Wurde in der Schule bereits behandelt,NaN,NaN,"know,in class","know,in class",NaN,v,NaN,NaN