import the 433 initial Chris's and I annotated data (starting from some questions) and adding all of those which do have missing questions with my annotations (Jade)

In [1]:
import pickle
import pandas as pd

In [7]:
jade = pd.read_csv('./jade_prior.csv', sep='\t', index_col=0)
prior = pd.read_csv('./correction.tsv', sep='\t', index_col=0)

In [8]:
jade.head()

,index,username,gender,year,field,beerslaw,jade_label,flag_jade_label
0,434,bezdgyya,1.0,2nd,Chemistry,Wir haben es im Unterricht behandelt und auch ...,"rusty,in class",1.0
1,435,y7p64n6z,4.0,2nd,Chemistry,Eher nicht so,"heard about,no mention",NaN
2,436,892r4czm,1.0,2nd,Chemistry,Einigermassen\r\nSchon mal angeschaut und Grun...,"rusty,no mention",NaN
3,437,uhbpoog9,1.0,1st,Chemistry,Ich habe es fast nicht gekannt,"don't know,no mention",NaN
4,438,bed4zkv2,1.0,1st,Chemistry,Über haubt nicht ich wusste noch nichts davon.,"don't know,no mention",NaN

In [9]:
prior.head()

,index,username,gender,year,field,beerslaw,Chris granular,Jade granular,flag_jade_label,flag_chris_label,decisions,D,FLAG
0,0,7sfwehhm,2.0,2nd,Chemistry,missing,unknown,unknown,NaN,NaN,v,NaN,NaN
1,1,786zpupn,1.0,1st,Chemistry,nicht sehr,don't know,don't know,NaN,NaN,v,NaN,NaN
2,2,pt2nbb4w,2.0,1st,Chemistry,Ich wusste noch nichts zu diesem Thema.,don't know,don't know,NaN,NaN,v,NaN,NaN
3,3,sqrqdsge,2.0,1st,Chemistry,Fast gar nicht,don't know,don't know,NaN,NaN,v,NaN,NaN
4,4,h8624awf,1.0,2nd,Biology,Gut,"know,no mention","know,no mention",NaN,NaN,v,NaN,NaN

In [15]:
jade['Chris granular'] = -1
jade['Jade granular'] = jade['jade_label']
jade['flag_chris_label'] = -1
jade['decisions'] = 'v'
jade['D'] = 'Was not sampled by Chris'
jade['flag'] = -1

In [16]:
prior = prior.append(jade)

In [19]:
prior = prior[[
    'index', 'username', 'gender', 'field', 'beerslaw', 'Chris granular',
    'Jade granular', 'flag_jade_label', 'flag_chris_label', 'decisions',
    'D', 'flag'
]]

In [20]:
prior

,index,username,gender,field,beerslaw,Chris granular,Jade granular,flag_jade_label,flag_chris_label,decisions,D,flag
0,0,7sfwehhm,2.0,Chemistry,missing,unknown,unknown,NaN,NaN,v,NaN,NaN
1,1,786zpupn,1.0,Chemistry,nicht sehr,don't know,don't know,NaN,NaN,v,NaN,NaN
2,2,pt2nbb4w,2.0,Chemistry,Ich wusste noch nichts zu diesem Thema.,don't know,don't know,NaN,NaN,v,NaN,NaN
3,3,sqrqdsge,2.0,Chemistry,Fast gar nicht,don't know,don't know,NaN,NaN,v,NaN,NaN
4,4,h8624awf,1.0,Biology,Gut,"know,no mention","know,no mention",NaN,NaN,v,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
46,480,2hr6mkdc,1.0,"Chemistry, Textiles",In der Berufsschule schon damit gerechnet\r\n1...,-1,"can use,in class,at work",NaN,-1.0,v,Was not sampled by Chris,-1.0
47,481,8nh4zvcp,1.0,"Chemistry, Textiles",Nicht so sehr damit vertraut.,-1,"don't know,no mention",NaN,-1.0,v,Was not sampled by Chris,-1.0
48,482,s2up6gmm,1.0,"Chemistry, Textiles","Eigentlich vertraut, allerdings war es schon e...",-1,"rusty,no mention",NaN,-1.0,v,Was not sampled by Chris,-1.0
49,483,47ce49e4,2.0,"Chemistry, Textiles","Im Unterricht durchgenommen, aber im Laboralta...",-1,"know,in class",NaN,-1.0,v,Was not sampled by Chris,-1.0
50,484,fj5tdybn,1.0,"Chemistry, Textiles",Halb-halb wir hatten es vor etwa 1.5 Jahren im...,-1,"rusty,in class",NaN,-1.0,v,Was not sampled by Chris,-1.0

In [21]:
prior.to_csv('./prior.tsv', sep='\t')